### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Unforgiven13** [MidnightsFX/Valheim_Armory#5]
A silver atgeir is missing from the game and a more fitting inventory icon for the surtling arrows. Something that shows they use surtling cores, like a red/yellow flame. The current one is almost identical to Obsidian arrow, though the back side, looks good I might add. The tip needs some love.
I have one if you are interested. It has the right size 64x64 png with no background:

![flame arrow](https://user-images.githubusercontent.com/123122898/232338158-fc573b6c-1385-4a60-817c-caba819cfd34.png)

**Comment by MidnightsFX** [comment]
Excellent points! Its been quite a while since I revisited the arrows, I'll see about updating the icons. I've been meaning to go back an re-mesh the arrows a little more and make them feel more unique.

As for the silver atgeir that is something I had noted and part of the reason the chitin atgeir is silver level. Which I have also been meaning to revisit. But I don't see any downside to adding a plain silver atgeir.

I've been pretty busy with the first boss weapons update, but after I do that update I plan on doing some TLC for other existing things etc and I think all of this stuff falls under that. I don't have a timeline, but shouldn't be too long after the first boss weapon update.

**Comment by MidnightsFX** [comment]
Still planning on working on the silver atgeir, potentially next update.

**Comment by MidnightsFX** [comment]
![image](https://github.com/MidnightsFX/Valheim_Armory/assets/9042626/91f2f69c-f245-493b-bc63-260d58dd98df)

planning on including this as a silver atgeir in the next update.

**Comment by MidnightsFX** [comment]
now available in 1.4.0!
