### ISSUE TITLE
Weapon balance

### ISSUE THREAD

**Issue by Bumbletr0n** [MidnightsFX/Valheim_Armory#9]
Hey, Midnight, 
I don't know if it's intentional, but most of your weapons are incredibly overpowered; specifically boss weapons. 
Eikthyr bow does more total damage than a Draugr fang
Eikthyr great axe > Iron axe
Royal abyssal atgeir > blackmetal atgeir
Eikthyr's charge > iron atgeir
Eikthy's spike > Blackmetal sword 
Moder's bite > Mistwalker and Jotun Bane

I could continue going through the list but I hope you see my point. 

I've been adjusting the config files to make the weapons do 25% less damage and double the cost, That's after increasing enemy health by 40% and damage by 25%. 

I really appreciate all the hard work, but please consider balancing properly. 
Thank you!

**Comment by MidnightsFX** [comment]
Hey!

I am actually super interested in improving the balance. Its been quite some time since I've actually had time to play the content, and I've mostly just approximated better than x.

Which I know is leaning towards overpowered, and I'd like to balance that closer to vanilla, but still make it feel good and interesting.

If you have specific damage settings/costs for the weapons you feel are balanced feel free to mention and we can go over them and I'll get the defaults updated.

**Comment by MidnightsFX** [comment]
I've pushed a balance change (1.3.3) as part of the default configurations for most boss weapons and some others that overall increases costs and brings them in line with what they should be tier wise.

As always I am still down to debate defaults for balancing, everyone likes things a little differently but the closer I can get to a seamless vanilla+ experience the better in my book.
